# Docker Compose file for webapp application development
# DON'T USE IN PRODUCTION ENVIRONMENT
# =================================================================
version: "3.1"
services:
    php-fpm:
      build: docker/php-fpm
      container_name: ${PROJECT_NAME}-php-fpm
      working_dir: /application
      volumes:
        - ${PROJECT_PATH}/application:/application
        - ${PROJECT_PATH}/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      env_file:
        - .env

    webserver:
      image: nginx:alpine
      container_name: ${PROJECT_NAME}-nginx
      working_dir: /application
      volumes:
        - ${PROJECT_PATH}/application:/application
        - ${PROJECT_PATH}/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "1025:80"
      env_file:
        - .env

    mysql:
      image: mysql:8.0
      container_name: ${PROJECT_NAME}-mysql
      # in case of Win10Home host (problem with volumes)
      command: "--innodb_use_native_aio=0"
      working_dir: /application
      volumes:
        - ${PROJECT_PATH}/application:/application
        - ${PROJECT_PATH}/data/mysql:/var/lib/mysql
      ports:
        - "1027:3306"
      env_file:
        - .env
